version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: yousranmz/portfolio_web:latest
    volumes:
      - .:/var/www/html
      - ssl:/etc/apache2/
      - certs:/etc/letsencrypt/live/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABD1CK0uS1
2wHJxkHusgHeJsAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAILJgkZTwSy33gJ8a
yHp++HBSmLWmEfpmuNWHuBcyfNQRAAAAoDZ3+MGcubY
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABD1CK0uS1
2wHJxkHusgHeJsAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAILJgkZTwSy33gJ8a
yHp++HBSmLWmEfpmuNWHuBcyfNQRAAAAoDZ3+MGcubY
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata:
  ssl:
  certs:
