  services:
    web:
      build:
        context: .
        args:
          uid: ${UID}
        dockerfile: Dockerfile.production
      image: yousranmz/portfolio_web:latest
      volumes:
        - .:/var/www/html
      ports:
        - "8080:80"
      depends_on:
        - db

    db:
      image: mysql:8.3
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: secret
      volumes:
        - dbdata:/var/lib/mysql
      ports:
        - "3306:3306"

  volumes:
    dbdata:
