name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  prepare-docker-buildx:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: prepare-docker-buildx
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yaml build
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose -f docker-compose.yaml push

  ssh-into-production-server:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: SSH into production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}

  update-docker-compose-and-restart-containers:
    runs-on: ubuntu-latest
    needs: ssh-into-production-server
    steps:
      - name: SSH into production server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: sembarang12
          script: |
            cd /opt/web-portfolio
            docker-compose -f docker-compose.yaml pull
            docker-compose -f docker-compose.yaml up -d

