name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yaml build
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose -f docker-compose.yaml push

  

