name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yaml build
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker-compose -f docker-compose.yaml push

      - name: List Docker images
        run: docker images

  update-docker-compose-and-restart-containers:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: SSH into production server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: sembarang12
          script: |
            cd /opt/web-portfolio
            git pull origin production
            docker-compose -f docker-compose.yaml pull
            docker-compose -f docker-compose.yaml up -d
